# ==============================================================================
# Terraform CD Pipeline
# ==============================================================================

name: Terraform CD

# ==============================================================================
# Pipeline Trigger
# ==============================================================================

on:

  push:
    branches:
      - main

# ==============================================================================
# GitHub Actions Permissions
# ==============================================================================

permissions:

  contents: read
  id-token: write

jobs:

  terraform-cd:

    name: Terraform CD
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform

    steps:

# ==============================================================================
# Checkout Repository
# ==============================================================================

      - name: Checkout Repository
        uses: actions/checkout@v4

# ==============================================================================
# Azure Login using OIDC
# ==============================================================================

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

# ==============================================================================
# Verify Azure Authentication
# ==============================================================================

      - name: Verify Azure Login
        run: az account show

# ==============================================================================
# Setup Terraform
# ==============================================================================

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

# ==============================================================================
# Terraform Initialization
# ==============================================================================

      - name: Terraform Init
        run: terraform init

# ==============================================================================
# Terraform Plan
# ==============================================================================

      - name: Terraform Plan
        run: terraform plan -input=false

